// RegistrationElderlyUniversityCourse/src/components/Empty.vue
<script setup lang="ts">
import { Inbox } from 'lucide-vue-next'

defineProps<{
  message?: string
}>()
</script>

<template>
  <div class="flex flex-col items-center justify-center py-16 text-secondary-light">
    <Inbox class="w-16 h-16 mb-4 text-cream-dark" />
    <p class="text-xl2">{{ message || '暂无数据' }}</p>
  </div>
</template>

// CollaborativeCurationArtExhibition/src/components/Empty.tsx
import { Inbox } from 'lucide-react';
import { cn } from '@/lib/utils';

interface EmptyProps {
  message?: string;
  className?: string;
}

export default function Empty({ message = '暂无数据', className }: EmptyProps) {
  return (
    <div className={cn('flex flex-col items-center justify-center py-16 text-gray-400', className)}>
      <Inbox size={48} strokeWidth={1.5} className="mb-3" />
      <p className="text-sm">{message}</p>
    </div>
  );
}
